export interface OcrLanguage {
  code: string
  name: string
  nativeName?: string
}

export const DEFAULT_OCR_LANGUAGES = ["vie", "eng"]

export const OCR_LANGUAGES: OcrLanguage[] = [
  { code: "afr", name: "Afrikaans" },
  { code: "amh", name: "Amharic", nativeName: "አማርኛ" },
  { code: "ara", name: "Arabic", nativeName: "العربية" },
  { code: "asm", name: "Assamese", nativeName: "অসমীয়া" },
  { code: "aze", name: "Azerbaijani", nativeName: "Azərbaycanca" },
  { code: "aze_cyrl", name: "Azerbaijani (Cyrillic)" },
  { code: "bel", name: "Belarusian", nativeName: "Беларуская" },
  { code: "ben", name: "Bengali", nativeName: "বাংলা" },
  { code: "bod", name: "Tibetan", nativeName: "བོད་ཡིག" },
  { code: "bos", name: "Bosnian", nativeName: "Bosanski" },
  { code: "bre", name: "Breton", nativeName: "Brezhoneg" },
  { code: "bul", name: "Bulgarian", nativeName: "Български" },
  { code: "cat", name: "Catalan", nativeName: "Català" },
  { code: "ceb", name: "Cebuano" },
  { code: "ces", name: "Czech", nativeName: "Čeština" },
  { code: "chi_sim", name: "Chinese (Simplified)", nativeName: "简体中文" },
  { code: "chi_sim_vert", name: "Chinese Simplified (Vertical)" },
  { code: "chi_tra", name: "Chinese (Traditional)", nativeName: "繁體中文" },
  { code: "chi_tra_vert", name: "Chinese Traditional (Vertical)" },
  { code: "chr", name: "Cherokee", nativeName: "ᏣᎳᎩ" },
  { code: "cos", name: "Corsican", nativeName: "Corsu" },
  { code: "cym", name: "Welsh", nativeName: "Cymraeg" },
  { code: "dan", name: "Danish", nativeName: "Dansk" },
  { code: "deu", name: "German", nativeName: "Deutsch" },
  { code: "div", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "dzo", name: "Dzongkha", nativeName: "རྫོང་ཁ" },
  { code: "ell", name: "Greek", nativeName: "Ελληνικά" },
  { code: "eng", name: "English" },
  { code: "enm", name: "English (Middle)" },
  { code: "epo", name: "Esperanto" },
  { code: "est", name: "Estonian", nativeName: "Eesti" },
  { code: "eus", name: "Basque", nativeName: "Euskara" },
  { code: "fao", name: "Faroese", nativeName: "Føroyskt" },
  { code: "fas", name: "Persian", nativeName: "فارسی" },
  { code: "fil", name: "Filipino" },
  { code: "fin", name: "Finnish", nativeName: "Suomi" },
  { code: "fra", name: "French", nativeName: "Français" },
  { code: "frk", name: "German Fraktur" },
  { code: "frm", name: "French (Middle)" },
  { code: "fry", name: "Western Frisian", nativeName: "Frysk" },
  { code: "gla", name: "Scottish Gaelic", nativeName: "Gàidhlig" },
  { code: "gle", name: "Irish", nativeName: "Gaeilge" },
  { code: "glg", name: "Galician", nativeName: "Galego" },
  { code: "grc", name: "Ancient Greek" },
  { code: "guj", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "hat", name: "Haitian", nativeName: "Kreyòl ayisyen" },
  { code: "heb", name: "Hebrew", nativeName: "עברית" },
  { code: "hin", name: "Hindi", nativeName: "हिन्दी" },
  { code: "hrv", name: "Croatian", nativeName: "Hrvatski" },
  { code: "hun", name: "Hungarian", nativeName: "Magyar" },
  { code: "hye", name: "Armenian", nativeName: "Հայերեն" },
  { code: "iku", name: "Inuktitut", nativeName: "ᐃᓄᒃᑎᑐᑦ" },
  { code: "ind", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "isl", name: "Icelandic", nativeName: "Íslenska" },
  { code: "ita", name: "Italian", nativeName: "Italiano" },
  { code: "ita_old", name: "Italian (Old)" },
  { code: "jav", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "jpn", name: "Japanese", nativeName: "日本語" },
  { code: "jpn_vert", name: "Japanese (Vertical)" },
  { code: "kan", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "kat", name: "Georgian", nativeName: "ქართული" },
  { code: "kaz", name: "Kazakh", nativeName: "Қазақша" },
  { code: "khm", name: "Khmer", nativeName: "ខ្មែរ" },
  { code: "kir", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "kmr", name: "Kurdish (Kurmanji)", nativeName: "Kurmancî" },
  { code: "kor", name: "Korean", nativeName: "한국어" },
  { code: "kor_vert", name: "Korean (Vertical)" },
  { code: "lao", name: "Lao", nativeName: "ລາວ" },
  { code: "lat", name: "Latin", nativeName: "Latina" },
  { code: "lav", name: "Latvian", nativeName: "Latviešu" },
  { code: "lit", name: "Lithuanian", nativeName: "Lietuvių" },
  { code: "ltz", name: "Luxembourgish", nativeName: "Lëtzebuergesch" },
  { code: "mal", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "mar", name: "Marathi", nativeName: "मराठी" },
  { code: "mkd", name: "Macedonian", nativeName: "Македонски" },
  { code: "mlt", name: "Maltese", nativeName: "Malti" },
  { code: "mon", name: "Mongolian", nativeName: "Монгол" },
  { code: "mri", name: "Māori" },
  { code: "msa", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "mya", name: "Burmese", nativeName: "မြန်မာ" },
  { code: "nep", name: "Nepali", nativeName: "नेपाली" },
  { code: "nld", name: "Dutch", nativeName: "Nederlands" },
  { code: "nor", name: "Norwegian", nativeName: "Norsk" },
  { code: "oci", name: "Occitan", nativeName: "Occitan" },
  { code: "ori", name: "Odia", nativeName: "ଓଡ଼ିଆ" },
  { code: "pan", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "pol", name: "Polish", nativeName: "Polski" },
  { code: "por", name: "Portuguese", nativeName: "Português" },
  { code: "pus", name: "Pashto", nativeName: "پښتو" },
  { code: "que", name: "Quechua", nativeName: "Runa simi" },
  { code: "ron", name: "Romanian", nativeName: "Română" },
  { code: "rus", name: "Russian", nativeName: "Русский" },
  { code: "san", name: "Sanskrit", nativeName: "संस्कृतम्" },
  { code: "sin", name: "Sinhala", nativeName: "සිංහල" },
  { code: "slk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "slv", name: "Slovenian", nativeName: "Slovenščina" },
  { code: "snd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "spa", name: "Spanish", nativeName: "Español" },
  { code: "spa_old", name: "Spanish (Old)" },
  { code: "sqi", name: "Albanian", nativeName: "Shqip" },
  { code: "srp", name: "Serbian (Cyrillic)", nativeName: "Српски" },
  { code: "srp_latn", name: "Serbian (Latin)", nativeName: "Srpski" },
  { code: "sun", name: "Sundanese", nativeName: "Basa Sunda" },
  { code: "swa", name: "Swahili", nativeName: "Kiswahili" },
  { code: "swe", name: "Swedish", nativeName: "Svenska" },
  { code: "syr", name: "Syriac", nativeName: "ܣܘܪܝܝܐ" },
  { code: "tam", name: "Tamil", nativeName: "தமிழ்" },
  { code: "tat", name: "Tatar", nativeName: "Татарча" },
  { code: "tel", name: "Telugu", nativeName: "తెలుగు" },
  { code: "tgk", name: "Tajik", nativeName: "Тоҷикӣ" },
  { code: "tha", name: "Thai", nativeName: "ไทย" },
  { code: "tir", name: "Tigrinya", nativeName: "ትግርኛ" },
  { code: "ton", name: "Tongan", nativeName: "Lea faka-Tonga" },
  { code: "tur", name: "Turkish", nativeName: "Türkçe" },
  { code: "uig", name: "Uyghur", nativeName: "ئۇيغۇرچە" },
  { code: "ukr", name: "Ukrainian", nativeName: "Українська" },
  { code: "urd", name: "Urdu", nativeName: "اردو" },
  { code: "uzb", name: "Uzbek (Latin)", nativeName: "O‘zbekcha" },
  { code: "uzb_cyrl", name: "Uzbek (Cyrillic)", nativeName: "Ўзбекча" },
  { code: "vie", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "yid", name: "Yiddish", nativeName: "ייִדיש" },
  { code: "yor", name: "Yoruba", nativeName: "Yorùbá" },
]

const languageMap = new Map(OCR_LANGUAGES.map((language) => [language.code, language]))

export function getLanguageName(code: string) {
  return languageMap.get(code)?.nativeName || languageMap.get(code)?.name || code
}

export function isSupportedLanguage(code: string) {
  return languageMap.has(code)
}
